language: c

dist: xenial

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
     - libcurl4-openssl-dev
     - libsystemd-dev
     - libjson-glib-dev

env:
  - CMAKE_PARAMS=-DWITH_SYSTEMD=ON
  - CMAKE_PARAMS=-DWITH_SYSTEMD=OFF

script:
   - mkdir -p build
   - cd build
   - cmake $CMAKE_PARAMS .. 
   - make
   - cd -
   - ./uncrustify.sh && git diff --exit-code
   - cd test && ./rauc-hawkbit-updater.t -v
